### ISSUE TITLE
Unhandled method ID

### ISSUE THREAD

**Issue by Hamau** [Arctium-Emulation/Project-WoW#7]
I've set the realmlist to 127.0.0.1:8000 and I'm using the patched WowB. I'm running both the sandbox and WoW as an administrator. Whenever I try to log in with arctium@arctium and password arctium, I get a BLZ51914003 error ingame and a "Got unhandled method id for '7' for 'ConnectionService'" error in the sandbox. A little help please?

**Comment by Agladead** [comment]
I have the same
