### ISSUE TITLE
Mac OS X Compile error

### ISSUE THREAD

**Issue by LuigiElleBalotta** [Arctium-Emulation/Project-WoW#9]
Mac OS X Sierra (latest OS)

Using Xamarin Studio (latest version).

To implement .NET Core read this guide: http://lastexitcode.com/blog/2016/06/05/AspNetCoreRC2SupportInXamarinStudio/

Compile --> you get error (don't know why, Xamarin doesn't say anything).

I also use this add-in before use the addin from the previous link: https://github.com/mrward/monodevelop-dnx-addin/issues/32#issuecomment-226277050

**Comment by Fabi** [comment]
Xamarin has no official support for .NET Core and that extension is made for an old version.
I tried that one a while ago and noticed many bugs, so I switched to Visual Studio Core or back to Windows and Visual Studio.

The only thing we can do is to create a branch for the next preview of .NET Core and add support for the new .csproj files and Visual Studio for Mac Preview/VS 2017

**Comment by LuigiElleBalotta** [comment]
ok, we can leave open this issue until it's done.. 
(Sigh Parallels + Visual Studio = my pc is crying)

**Comment by Fabi** [comment]
Yep, I already opened a issue just for reference at https://github.com/Arctium-Emulation/Project-WoW/issues/8

**Comment by Fabi** [comment]
This one is fixed for the current preview 2 build and works on command line, VS Code & Rider. Closed for now
